/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Discover: typeof import('./src/components/Discover/Discover.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Favorites: typeof import('./src/components/Favorites/Favorites.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    GoTop: typeof import('./src/components/GoTop/GoTop.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    Modal: typeof import('./src/components/Header/Modal/Modal.vue')['default']
    MusicCollect: typeof import('./src/components/Musiclistdetail/MusicCollect/MusicCollect.vue')['default']
    Musiclist: typeof import('./src/components/Discover/Musiclist/Musiclist.vue')['default']
    MusicList: typeof import('./src/components/Musiclistdetail/MusicList/MusicList.vue')['default']
    Musiclistdetail: typeof import('./src/components/Musiclistdetail/Musiclistdetail.vue')['default']
    MusicReview: typeof import('./src/components/Musiclistdetail/MusicReview/MusicReview.vue')['default']
    NavBar: typeof import('./src/components/Discover/Singer/NavBar/NavBar.vue')['default']
    Personal: typeof import('./src/components/Personal/Personal.vue')['default']
    Ranking: typeof import('./src/components/Discover/Ranking/Ranking.vue')['default']
    Recommend: typeof import('./src/components/Discover/Recommend/Recommend.vue')['default']
    Recommendmusic: typeof import('./src/components/Recommendmusic/Recommendmusic.vue')['default']
    Review: typeof import('./src/components/Review/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderList: typeof import('./src/components/SiderList/SiderList.vue')['default']
    Singer: typeof import('./src/components/Discover/Singer/Singer.vue')['default']
    Video: typeof import('./src/components/Video/Video.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
